# Generated by Django 2.2.4 on 2020-05-11 15:19

from django.db import migrations


def load_owners(apps, schema_editor):
    Owner = apps.get_model('property', 'Owner')
    Flat = apps.get_model('property', 'Flat')
    for flat in Flat.objects.all():
        Owner.objects.get_or_create(
            owner=flat.owner,
            owner_phone_pure=flat.owner_phone_pure,
            defaults = {
                'owners_phonenumber': flat.owners_phonenumber,
            }
        )


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0009_owner'),
    ]

    operations = [
        migrations.RunPython(load_owners)
    ]
