# Generated by Django 2.2.4 on 2020-05-23 11:39

from django.db import migrations


def flat_and_owner(apps, schema_editor):
    Owner = apps.get_model('property', 'Owner')
    Flat = apps.get_model('property', 'Flat')
    for flat in Flat.objects.all():
        owners = Owner.objects.filter(
            owner=flat.owner,
            owners_phonenumber=flat.owners_phonenumber
        )
        flat.owners.set(owners)


class Migration(migrations.Migration):
    dependencies = [
        ('property', '0011_auto_20200523_1437'),
    ]

    operations = [
        migrations.RunPython(flat_and_owner)
    ]
