# Generated by Django 2.2.4 on 2020-05-15 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0012_auto_20200512_1806'),
    ]

    operations = [
        migrations.RenameField(
            model_name="Owner",
            old_name="owner",
            new_name="fio",
        ),
        migrations.RenameField(
            model_name="Owner",
            old_name="owners_phonenumber",
            new_name="phonenumber",
        ),
        migrations.RenameField(
            model_name="Owner",
            old_name="owner_phone_pure",
            new_name="phone_pure",
        ),
    ]
