# Generated by Django 2.2.4 on 2020-05-21 10:11

from django.db import migrations


def owner_and_flat(apps, schema_editor):
    Owner = apps.get_model('property', 'Owner')
    Flat = apps.get_model('property', 'Flat')
    for flat in Flat.objects.all():
        owner = Owner.objects.filter(id=flat.id)
        flat.owners.set(owner)


class Migration(migrations.Migration):
    dependencies = [
        ('property', '0014_auto_20200521_1310'),
    ]

    operations = [
        migrations.RunPython(owner_and_flat)
    ]
